### ISSUE TITLE
how to get all the vulnerabilities from the pyvas report

### ISSUE THREAD

**Issue by ash84** [mpicard/pyvas#15]
I am able to read a report using PyVAS, the `reports = cli.list_reports()` returns all the available reports, I'm traversing through each one of them `reports.data[i]['report']['results']['result']` and I see only 10 of the vulnerabilities, how do I get all of them using PyVAS?

**Comment by mpicard** [comment]
Hm I don't have openvas setup right now. I'd be happy to take a PR if you find the issue though

**Comment by jal58** [comment]
I've been working on a fork of pyvas, and will be looking at extracting details from `list_reports()`.  It may be an issue with passing parameters to OMP.  As I've had to rewrite `get_config()` in order to extract all the information possible.

**Comment by mpicard** [comment]
Awesome! PRs are always welcome! I haven’t had time to dig into this too
much but I’d be happy to review a fix and merge it!

**Comment by jal58** [comment]
Thanks, it might be helpful to email about this: you can find my email here 
https://privnote.com/R6oVzTP3#1XBdD7l3Z
I'm working on replacing Nessus with OpenVAS on our automatic probing system.

**Comment by mpicard** [comment]
Expired, you can email me at martin8768@gmail.com if you want

**Comment by ash84** [comment]
I was able to get all the vulnerabilities through `get_reports()`
```
    ovas_report = cli.get_report(report['report']['@id'])
    for result in ovas_report.data['report']['results']['result']:
        ...
```

**Comment by jal58** [comment]
Hey ash84, thank you!
