### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by jal58** [mpicard/pyvas#17]
I'm having trouble running the tests.  I've got it to the point where I can run pytest on it, but it fails.  I have a working OpenVAS instance and the host I'm trying to run the tests on can talk to it successfully with omp. I wonder if you have any advice on getting this to run successfully please?

This is what I get when I run it with python3 -m pytest from a fresh clone of your repo.
[results.txt](https://github.com/mpicard/pyvas/files/1996018/results.txt)

Thanks!

Anna

**Comment by jal58** [comment]
Sorry, I've sorted this out now.

**Comment by jal58** [comment]
It was a combination of that and packages. I've been keeping track of what I've done.  Now I'm working on writing tests for all the functions that I've written...

**Comment by mpicard** [comment]
Awesome! That’s great news I’m sorry I don’t have the time this project
deserves at the moment so I glad someone is adding more functionality and
tests!

**Comment by jal58** [comment]
Thanks Martin!

A bit of background about what I’m doing, for your information.  We have a system that was built around Nessus using it’s REST API, which automates setting up scans and policies, and then presents the results over the web to the people responsible for the machines that have been scanned.  Nessus is both changing its licensing model, and removing the API, so it will soon be untenable (pun intended) to carry on in this manner.  In the short term, I’m working on replacing Nessus with OpenVAS, which involves rewriting the components of our system to interface with OpenVAS, which demands more functionality than pyvas currently offers, so I’m working on that too.

One thing that Nessus does is refer to things by name rather than ids.  So rather than put a lot of awkward logic into my scripts, I’m trying to do it only once by creating _by_name functions in pyvas, that mimic this.

Thank you for developing pyvas and sharing it with the world, it’s making my life a lot easier than it would have been otherwise!

Anna

**Comment by mpicard** [comment]
Very cool! I was doing something similar with a REST based service that needed to talk to openvas but found nothing that worked so I created this and I’m glad it’s of help to you! Your privnote expired but you can email me at martin8768@gmail.com or I’ll leave this Issue open for discussion. Unfortunately I moved on to other things so I don’t have the time but I’m so happy to hear that there is enough core functionality to easily let other contributors add more command support and higher level APIs.
