### ISSUE TITLE
Usage doesn't work

### ISSUE THREAD

**Issue by p420lch3** [mpicard/pyvas#2]
> from pyvas import _**client**_
> with **_client_**(hostname, username='username', password='password') as cli:
>        r = cli.list_tasks()
>        r.ok

TypeError: 'module' object is not callable

It should be :
>from pyvas import **_*_**
>with **_Client_**(hostname, username='username', password='password') as cli:

OR:

>import pyvas
>with **_pyvas.Client_**("127.0.0.1", username='admin', password='123123') as cli:

**Comment by mpicard** [comment]
Thanks, fixed!

**Comment by mpicard** [comment]
Do you use this library? I'd be curious to know if there's anything missing, I don't have the full protocol implemented but I was going to eventually do some transformation of the spec into generic pythonic interfaces when I had the time.

**Comment by p420lch3** [comment]
I would like to use this library to build auto scanning program.
Can you provide some examples to create scanning task.

**Comment by mpicard** [comment]
You can look at the tests for examples, basically you need to 

```python
config = client.create_config(name='name')
target = client.create_target(name='', hosts='0.0.0.0,127.0.1.1')
task = client.create_task(name='task', target_uuid=["@id"], config_uuid=config["@id"]) 
resp = client.start_task(uuid=task["@id"])
assert resp.ok
print(resp)
```
https://github.com/mpicard/pyvas/blob/master/tests/test_client.py
