### ISSUE TITLE
Connect to omp client running on a different host on the network

### ISSUE THREAD

**Issue by kounelios13** [mpicard/pyvas#21]
Hello.I am in an office in which we have a vm running `OpenVas`.
My question is whether I can connect to the omp client running in that vm from a different machine.

I tried to use the following code

```
HOST='an ip address'
with Client(host=HOST,username='username',password='password') as cli:
    cli.list_tasks()
```
however I get a Connection timedout error(Errno 110).

Any ideas if that's possible?
If it is I would appreciate a code snippet

**Comment by jal58** [comment]
Hello, you may find this doc from my fork of pyvas helpful (I'm hoping that this fork will get pulled in soon).  It isn't that difficult to set up, but I found that the available documentation wasn't helpful, so I tried to document what worked for me, so others could benefit.  Hope it helps you!

https://github.com/jal58/pyvas/blob/master/doc/testing.md

**Comment by mpicard** [comment]
Closing for now due to inactivity
